In [7]:
with open('untitled.txt','r') as f:
    var=f.read() 
var=var.split() 
d={}
for i in var: 
    if i in d:
        d[i]+=1
    else:
        d[i]=1
print(d)

{'Dead': 1, 'or': 9, 'Low': 1, 'Batteries': 1, '(The': 1, '#1': 1, 'Cause)': 1, 'The': 5, 'power': 2, 'in': 1, 'the': 16, 'batteries': 1, 'is': 6, 'first': 1, 'thing': 1, 'to': 5, 'go.': 1, 'Even': 1, 'if': 1, 'they': 1, 'have': 2, 'some': 2, 'left,': 1, 'it': 3, 'might': 2, 'not': 1, 'be': 3, 'enough': 1, 'send': 2, 'a': 4, 'strong': 1, 'signal.': 3, 'Blocked': 2, 'Signal': 2, 'Emitter': 1, 'remote': 2, 'sends': 1, 'an': 1, 'invisible': 1, 'infrared': 2, '(IR)': 1, 'light': 2, 'signal': 3, 'from': 2, 'small': 2, 'bulb': 1, 'at': 1, 'front.': 1, 'If': 4, 'this': 2, 'blocked,': 2, "can't": 2, 'get': 3, 'out.': 1, 'Stuck': 1, 'Button': 1, 'one': 1, 'button': 1, 'partially': 1, 'pressed': 1, 'stuck': 1, 'down,': 1, 'can': 5, 'continuous': 1, 'that': 4, 'confuses': 1, 'TV': 5, 'and': 2, 'stops': 1, 'other': 1, 'buttons': 1, 'working.': 1, 'Remote': 1, 'Needs': 1, 'Be': 1, 'Reset': 1, 'Re-Paired': 1, 'Modern': 1, 'smart': 1, 'TVs': 1, 'often': 1, 'use': 1, 'Bluetooth': 1, 'Radio': 1, 'Frequency': 1, '(RF)': 1, 'remotes': 1, 'are': 1, '"paired"': 1, 'TV.': 1, 'This': 1, 'connection': 1, 'sometimes': 2, 'lost.': 1, 'Physical': 1, 'Damage': 1, 'Remotes': 1, 'dropped,': 1, 'sat': 1, 'on,': 1, 'drinks': 1, 'spilled': 1, 'on': 3, 'them.': 1, 'Internal': 1, 'components': 1, 'break': 1, 'corrode.': 1, 'Category': 1, '2:': 1, 'Issues': 1, 'with': 2, 'Environment': 1, "you're": 1, 'sure': 1, 'fine,': 1, 'problem': 1, 'receiving': 1, 'end.': 1, 'Sensor': 1, 'has': 1, 'sensor': 1, '(usually': 1, 'bottom': 1, 'frame)': 1, 'receives': 1, "remote's": 2, '"see"': 1, 'commands.': 2, "TV's": 2, 'Software': 1, 'Glitching': 1, 'Sometimes,': 1, 'internal': 1, 'software': 1, 'freeze': 1, 'stuck,': 1, 'making': 1, 'unresponsive': 1, 'any': 1, 'Interference': 1, 'Bright': 1, 'sunlight': 1, 'certain': 1, 'types': 1, 'of': 1, 'overhead': 1, 'lighting': 1, '(especially': 1, 'energy-efficient': 1, 'fluorescent': 1, 'LED': 1, 'bulbs)': 1, 'emit': 1, 'interferes': 1}

In [1]:
import pandas as pd

In [4]:
df=pd.read_csv(r"C:\Users\masir\Downloads\coffee_shop_sales2.csv")

In [5]:
df

         Day  Cups Sold  Avg Temp (°C) FootBall Match (Yes/No)
0     Monday        154             24                      No
1    Tuesday        143             23                      No
2  Wednesday        166             26                      No
3   Thursday        142             22                      No
4     Friday        203             33                     Yes
5   Saturday        214             34                     Yes
6     Sunday        202             32                     Yes

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\masir\appdata\roaming\python\python312\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\masir\appdata\roaming\python\python312\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\masir\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\masir\appdata\roaming\python\python312\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\masir\appdata\roaming\python\python312\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\masir\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv(r"C:\Users\masir\Downloads\loan_data_set.csv")

In [5]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

**Problem Statement**

**About Company**

Dream Housing Finance company deals in all home loans. They have presence across all urban, semi urban and rural areas. Customer first apply for home loan after that company validates the customer eligibility for loan.

**Problem**


* Company wants to automate the loan eligibility process (real time) based on customer detail provided while filling online application form.
* These details are Gender, Marital Status, Education, Number of Dependents, Income, Loan Amount, Credit History and others.
* To automate this process, they have given a problem to identify the customers segments, those are eligible for loan amount so that they can specifically target these customers.``

In [6]:
df['ApplicantIncome'].mean()

5403.459283387622

In [9]:
df['Gender'].value_counts()

Gender
Male      489
Female    112
Name: count, dtype: int64

In [10]:
df['Education'].value_counts()

Education
Graduate        480
Not Graduate    134
Name: count, dtype: int64

In [11]:
pd.crosstab(df['Gender'],df['Loan_Status'])

Loan_Status    N    Y
Gender
Female        37   75
Male         150  339

In [14]:
pd.crosstab(df['Loan_Status'],df['Education'])

Education    Graduate  Not Graduate
Loan_Status
N                 140            52
Y                 340            82

In [15]:
pd.crosstab(df['Loan_Status'], [df['Education'], df['Gender']])

Education   Graduate      Not Graduate
Gender        Female Male       Female Male
Loan_Status
N                 31  105            6   45
Y                 61  271           14   68

In [18]:
df.groupby(["Gender","Property_Area"])[['ApplicantIncome','CoapplicantIncome']].max()

                      ApplicantIncome  CoapplicantIncome
Gender Property_Area
Female Rural                    10000             3683.0
       Semiurban                19484             8980.0
       Urban                    18165            41667.0
Male   Rural                    81000             8333.0
       Semiurban                39999            20000.0
       Urban                    63337            33837.0